### ISSUE TITLE
stable branch not building.

### ISSUE THREAD

**Issue by maclema** [dcm4che/dcm4chee-monitoring#1]
The stable branch is currently not building as there are tests failing which have be fixed in master. (Fixed in https://github.com/dcm4che/dcm4chee-monitoring/commit/f158ceb84f1d04cccc8ecadc2f88e92af41e2c3e)

**Comment by hczedik** [comment]
Stable is currently not getting updated. Please use the master branch.

**Comment by maclema** [comment]
Thank you  - Is the stable branch in the other repos being updated or should I build everything from master for 4.5.0?

**Comment by hczedik** [comment]
The stable branch is abandoned in all repos at the moment. Yes, please build everything from master.
